version: "3.1"
volumes:
  postgres: ~
services:
  nginx:
    container_name: billing.study-on.local
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ./docker/hosts/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/hosts/symfony:/etc/nginx/symfony
    ports:
      - "${NGINX_PORT}:80"
    links:
      - php
  postgres:
    container_name: billing_study_on_postgres
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  php:
    container_name: billing_study_on_php
    build: docker/images/php
    working_dir: /app
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ${PWD}:/app
      - ${HOME}/.composer:/.composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    links:
      - postgres
  mailhog:
    container_name: 'mailhog'
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"